name: PlayerPlot
version: 1.18.0
main: com.eclipsekingdom.playerplot.PlayerPlot
api-version: 1.13
authors: [ sword7 ]
description: A plugin that adds protected areas for player use.
website: https://eclipsekingdom.com
load: POSTWORLD
softdepend: [ dynmap ]

commands:
  pplot:
    description: edit plots
  plot:
    description: edit plots
  toplot:
    description: teleport to plot
  playerplot:
    description: show plugin commands
  plotdeed:
    description: summon plot deeds
  writedeed:
    description: write plot deeds

permissions:
  playerplot.*:
    description: grants all player plot user
    default: op
  playerplot.loot:
    description: grants access to the /plotdeed
    default: op
  playerplot.access:
    description: grants access to all player's plots
    default: op
  playerplot.teleport:
    description: grants access to teleportation commands
    default: op
  playerplot.update:
    description: grants access to /playerplot update
    default: op
  playerplot.reload:
    description: grants access to /playerplot reload
    default: op
  playerplot.write:
    description: grants access to /writedeed
