name: PlayerPlot
version: 1.17.1
main: com.eclipsekingdom.playerplot.PlayerPlot
api-version: 1.13
authors: [sword]
description: A plugin that adds protected areas for player use
website: eclipsekingdom.com
load: POSTWORLD
softdepend: [dynmap]

commands:
  plot:
    description: edit plots
  rplot:
    description: edit remote plots
  playerplot:
    description: show plugin commands
  plotdeed:
    description: summon plot deed(s)
    permission: playerplot.loot

permissions:
  playerplot.*:
    description: grants all player plot user
  playerplot.loot:
    description: grants access to the /plotdeed command
    default: op
  playerplot.access:
    description: grants access to all player's plots
    default: op